### ISSUE TITLE
Segmentation fault while training DualRL

### ISSUE THREAD

**Issue by Karlguo** [luofuli/DualRL#2]
I go through step 1 and 2 normally, but when I training the model for Dual RL, I got a segmentation fault like this:
![image](https://user-images.githubusercontent.com/11541136/59759971-cd2bf980-92c3-11e9-84ec-2983f0294453.png)

**Comment by luofuli** [comment]
I did not get any error when I was running the code of DualRL. And I have not encountered a segmentation error before.
However, since segmentation fault is a common and annoying problem of tensorflow, I strongly suggest that you try the following solutions: https://github.com/tensorflow/tensorflow/issues?utf8=%E2%9C%93&q=Segmentation+fault
Or can you provide more details? I will try my best to help you solve it.
- Linux version
- TensorFlow version and installed from where
- CUDA/cuDNN version
- GPU model and memory
