### ISSUE TITLE
How to evaluate on dev set and use early stopping

### ISSUE THREAD

**Issue by Surabhi-Kumari** [luofuli/DualRL#22]
I have gone through your code. In dual_training.py you are evaluating on test set not on dev set and code is run for 10 epoch. But, in paper it is  mentioned that  you are using early stopping on dev set performance with patience=1. Can you elaborated which performance. Is there any references data for dev set to calculated BLEU score on dev set.
Thanks in advance.

**Comment by luofuli** [comment]
The GYAFC dataset has a dev set and we perform early stopping on its dev set to choose the hypermeters. However, since YELP doesn't have a dev set, we don't perform early stopping on this dataset. Considering the generality of the code, we dropped the early stopping when releasing the code. Note that we evaluate on the test set for both datasets to let other followers easily see the performance of the model on the fly to **avoid mode collapse of RL** (which always happens under an RL framework, for example, a not good warm-up), not for choosing hypermeters or checkpoints.
